server:
  port: 8080

spring:
  application:
    name: mdp
  profiles:
    active: dev
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    # dynamic-datasource-spring-boot-starter 动态数据源的配置内容
    dynamic:
      #默认主的数据源
      primary: master
      #监控springboot数据库操作
      p6spy: true
      druid:
        #初始化时建立物理连接的个数;初始化发生在显示调用init方法，或者第一次getConnection时
        initial-size: 5
        #最大和最小连接池数量
        min-idle: 5
        max-active: 20
        #获取连接等待超时时间,配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
        max-wait: 6000
        #间隔多久进行空闲检测，时间单位：毫秒
        time-between-eviction-runs-millis: 6000
        #一个连接在池中最小生存时间
        min-evictable-idle-time-millis: 300000
        #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会启作用
        validation-query: select 1 from dual
        #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
        test-while-idle: true
        #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        test-on-borrow: false
        #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        test-on-return: false
        #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        #通过别名的方式配置扩展插件，常用的插件有： 监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
        filters: stat,wall,slf4j
        #打开mergeSql功能和慢sql
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        # 合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
          username: root
          password: 123456
          driverClassName: com.mysql.jdbc.Driver
        cluster:
          url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
          username: root
          password: 123456
          driverClassName: com.mysql.jdbc.Driver


#mybatis-plus配置
mybatis-plus:
  #mapper文件路径
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.boot.mdp.**.entities
  type-enums-package:
  global-config:
    db-config:
      #主键类型
      id-type: uuid
      #字段策略
      select-strategy: not_empty
      #驼峰格式
#      column-format: underline
      #逻辑删除
      logic-delete-value: 0
      logic-not-delete-value: 1
  #原生配置
  configuration:
    #自动转换
    map-underscore-to-camel-case: true
    #二级缓存
    cache-enabled: false
    #查询为空返回null
    call-setters-on-nulls: true

